### ISSUE TITLE
playbook spec

### ISSUE THREAD

**Issue by mb-wali** [cyverse-austria/ansible-es#1]
* single node
* install elasticsearch version `elasticsearch:5.6.14`
* using the following configs:
```bash
ES_JAVA_OPTS="-Xms4g -Xmx4g"
timezone=Europe/Vienna (configure on vm if not already configured)
sysctl -w vm.max_map_count=262144
ports=9200,9300
```

**Comment by mb-wali** [comment]
* make sure docker is installed
* make sure docker-compose is installed
* create docker-compose file: `es-compose.yml`
```yaml
version: '2.2'
services:


  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"

```
* run docker-compose command
`docker-compose -f es-compose.yml up -d`
* indexing:
settings.json:  
https://cyverse-austria.github.io/docs/deployments/elasticsearch/#preq_1 

```bash
# delete existing index
curl -sX DELETE "http://qa-elasticsearch.cyverse.at:9200/*"

# reindex 
curl -sX PUT "http://qa-elasticsearch.cyverse.at:9200/data" -d @settings.json
```
